# Site settings
title: The Peace Corps ICT4D Playbook
short_title: ICT4D Playbook
description: |
    The ICT4D Playbook provides Peace Corps Volunteers and staff with principles, projects, and resource toolkits for using data and technology most effectively in their service.
baseurl: http://peacecorps.github.io/ict4d-playbook
github_username:  peacecorps
github_repo:  ict4d-playbook

# devs:
#   -
#       name: Gabriel Kriueshok
#       github: gabrielkrieshok

# contributors:
#   -
#       name: 
#       link: 

#googleanalytics: UA-XXXXX-X

markdown: kramdown

permalink: pretty

defaults:
  -
    scope:
      path: "guide"
    values:
      layout: guide
      section: guide
  -
    scope:
      path: "posts"
    values:
      layout: post
      section: posts
  -
    scope:
      path: "toolkits"
    values:
      layout: toolkit
      section: toolkits
  -
    scope:
      path: "resources"
    values:
      layout: toolkit
      section: resources
  -

    scope:
      path: "projects"
    values:
      layout: project
      section: projects
  -
    scope:
      path: ""
    values:
      layout: default
      section:
  -
    scope:
      path: "community"
    values:
      layout: post
      section: community
# related_projects:
#   -
#       name: 
#       link: 