# Site settings
title: The Peace Corps ICT4D Playbook
short_title: ICT4D Playbook
description: |
    Resources for Peace Corps Volunteers leveraging information, communication, and technology for development
baseurl: http://peacecorps.github.io/ict4d-playbook
github_username:  peacecorps
github_repo:  ict4d-playbook

# devs:
#   -
#       name: Gabriel Kriueshok
#       github: gabrielkrieshok

# contributors:
#   -
#       name: 
#       link: 

#googleanalytics: UA-XXXXX-X

markdown: kramdown

permalink: pretty


meta:
  resources:
    label: resources
    output: true
    title: Resources
  toolkits:
    label: toolkits
  guide:
    label: guide
    output: true
    title: Guide
    toc:
      order:
        - introduction
        - strategy
        - principles
        - action-plan
        - program-areas
        - initiatives
      chapters:
        - title: 'Introduction'
          slug: 'introduction'
        - title: 'Strategy'
          slug: 'strategy'
        - title: 'Principles'
          slug: 'principles'
        - title: 'Action Plan'
          slug: 'action-plan'
        - title: "Program Areas"
          slug: 'program-areas'
        - title: 'Initiatives'
          slug: 'initiatives'
  contribute:
    label: contribute
    output: true
    title: Contribute
    has_translation: false
    toc:
      chapters:
        - title: 'Contributing To The Handbook'
        - title: 'Adding A Page'
          slug: 'adding'
        - title: 'Editing A Page'
          slug: 'editing'
        - title: 'Adding A Term To The Glossary'
          slug: 'add-term'
        - title: 'Adding A Resource To The Library'
          slug: 'add-resource'
        - title: 'Translating The Guide'
          slug: 'translate-guide'
        - title: 'Translating The Glossary'
          slug: 'translate-glossary'
        - title: 'Markdown Examples'
          slug: 'markdown-examples'



defaults:
  -
    scope:
      path: "guide"
    values:
      layout: guide
      section: guide
  -
    scope:
      path: "posts"
    values:
      layout: post
      section: posts
  -
    scope:
      path: "resources"
    values:
      layout: toolkit
      section: resources
  -
    scope:
      path: "projects"
    values:
      layout: project
      section: projects
  -
    scope:
      path: "community"
    values:
      layout: post
      section: community
  -
    scope:
      path: "toolkits"
    values:
      layout: post
      section: toolkit

# related_projects:

# collections:
#   toolkits:
#     output: true
#     permalink: /toolkits/:title/

#   -
#       name: 
#       link: 