# Site settings
title: The Peace Corps ICT4D Playbook
short_title: ICT4D Playbook
description: |
    Resources for Peace Corps Volunteers leveraging information, communication, and technology for development
baseurl: http://peacecorps.github.io/ict4d-playbook
github_username:  peacecorps
github_repo:  ict4d-playbook

# devs:
#   -
#       name: Gabriel Kriueshok
#       github: gabrielkrieshok

# contributors:
#   -
#       name: 
#       link: 

#googleanalytics: UA-XXXXX-X

markdown: kramdown

kramdown:
  parse_block_html: true

permalink: pretty


meta:
  guide:
    output: true
    toc:
      chapters:
        - title: 'Introduction'
          slug: 'introduction'
        - title: 'Why ICT4D?'
          slug: 'why-ict4d'
        - title: 'What is ICT4D?'
          slug: 'what-is-ict4d'
        - title: 'Approach'
          slug: 'approach'
        - title: 'Strategy'
          slug: 'strategy'
        - title: 'Principles'
          slug: 'principles'
        - title: "Program Areas Overview"
          slug: 'program-areas-overview'
        - title: 'Initiatives'
          slug: 'initiatives'
        - title: 'ICT4D for Volunteers'
          slug: 'ict4d-for-volunteers'
        - title: 'ICT4D for Staff'
          slug: 'ict4d-for-staff'
        - title: 'FAQ'
          slug: 'faq'
        - title: 'History'
          slug: 'history'
        - title: 'Glossary'
          slug: 'glossary'
  program-areas:
    output: true
    toc:
      chapters:
        - title: 'Digital Literacy'
          slug: 'digital-literacy'
        - title: 'ICTs for Education'
          slug: 'icts-for-education'
        - title: 'Technology for Monitoring & Evaluation'
          slug: 'technology-for-monitoring-and-evaluation'
        - title: 'Design Thinking'
          slug: 'design-thinking'
        - title: 'GIS and Mapping'
          slug: 'gis-and-mapping'
        - title: 'Girls and STEM Education'
          slug: 'girls-and-stem-education'
        - title: 'Mobile Communications'
          slug: 'mobile-communications'
        - title: 'Radio and Mass Media'
          slug: 'radio-and-mass-media'
        - title: 'Libraries and Maker Spaces'
          slug: 'libraries-and-maker-spaces'
        - title: 'Climate Change Education'
          slug: 'climate-change-education'
        - title: 'mHealth'
          slug: 'mhealth'
        - title: 'Media Production'
          slug: 'media-production'
        - title: 'Youth Workforce Employment'
          slug: 'youth-workforce-employment'
        - title: 'Appropriate Technology'
          slug: 'appropriate-technology'
  toolkits:
    output: true
    toc:
      chapters:
        - title: 'ICT4D Course'
          slug: 'ict4d-course'
        - title: 'Software and Apps for Volunteers'
          slug: 'software-and-apps-for-volunteers'
        - title: 'Starting An ICT4D Committee'
          slug: 'starting-an-ict4d-committee'
        - title: 'Web Tools And Services'
          slug: 'web-tools-and-services'
  volunteer-projects:
    output: true
    toc:
      chapters:
        - title: 'Bantu Babel - Zambia'
          slug: 'bantu-babel'
        - title: 'Let Girls Learn Hackathon - Ghana'
          slug: 'let-girls-learn-hackathon-ghana'
        - title: 'GirlTech - Uganda'
          slug: 'girltech'
        - title: 'Technovation Challenge - Moldova'
          slug: 'technovation-challenge'
        - title: 'Camp Sky - Malawi'
          slug: 'camp-sky'
        - title: 'Camp TechKobwa - Rwanda'
          slug: 'camp-techkobwa'
        - title: 'Other Projects'
          slug: 'other-projects'

  community:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: post
      section:
      authors:
  -
    scope:
      path: "guide"
    values:
      layout: post
      section: guide
  -
    scope:
      path: "program-areas"
    values:
      layout: post
      section: program-areas
  -
    scope:
      path: "toolkits"
    values:
      layout: post
      section: toolkit
      type: toolkit
  -
    scope:
      path: "volunteer-projects"
    values:
      layout: volunteer-project
      section: volunteer-projects
  -
    scope:
      path: "community"
    values:
      layout: post
      section: community

# related_projects:

# collections:
#   toolkits:
#     output: true
#     permalink: /toolkits/:title/

#   -
#       name: 
#       link: 